version: "3"
services:
  api:
    container_name: qrcode-service
    domainname: ${DOMAIN}
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=letsencrypt@${DOMAIN}
    expose:
      - 8080/tcp
    hostname: ${DOMAIN}
    image: ghcr.io/z720/qrcode-referer:${VERSION:-develop}
    labels:
    - traefik.enable=true
    - traefik.http.routers.qrcode-service.rule=Host(`${DOMAIN}`)
    - traefik.http.routers.qrcode-service.entrypoints=websecure
    - traefik.http.routers.qrcode-service.tls=true
    - traefik.http.routers.qrcode-service.tls.certresolver=letsencrypt  
    networks:
      - internet
networks:
  internet:
    external: true
    name: ${EXTERNAL_NETWORK}
